### ISSUE TITLE
Latest branch doesn't compile on Ubuntu 26.06

### ISSUE THREAD

**Issue by SaintShaggy** [wwivbbs/wwiv#1690]
Attempting to make and compile on Ubuntu 26.06 server throws compile errors.

/opt/wwiv/src/aug2026/wwiv/localui/curses_io.cpp: In member function ‘wwiv::local::ui::CursesWindow* wwiv::local::ui::CursesIO::CreateBoxedWindow(const std::string&, int, int) const’:
/opt/wwiv/src/aug2026/wwiv/localui/curses_io.cpp:212:106: error: invalid new-expression of abstract class type ‘wwiv::local::ui::CursesWindow’
  212 |   std::unique_ptr<CursesWindow> window(new CursesWindow(window_.get(), color_scheme_.get(), nlines, ncols));
      |                                                                                                          ^
[35/526] Building CXX object core/CMakeFiles/core.dir/os_unix.cpp.o
ninja: build stopped: subcommand failed

based on my search this appears to be caused by the newer compiler versions more strictly enforcing rules, in this case: CursesWindow as an unfinished "abstract class" because a virtual function signature in the system's updated ncurses header files has changed.

Options to include cmake parameters of -fpermissive intended to resolve these as warnings seem to fail.

Of course the genuine stupidity (AI) I am using could be completely wrong too.

I am going to attempt to compile it on a 24.04 version and copy the binaries over.
