### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by k5jat** [wwivbbs/wwiv#1083]
I just pulled the last update and get a compile error.

``  3%] Building CXX object core/CMakeFiles/core.dir/semaphore_file.cpp.o
In file included from /home/wwiv/git/core/semaphore_file.cpp:19:0:
/home/wwiv/git/core/../core/semaphore_file.h:34:59: error: expected class-name before ΓÇÿ{ΓÇÖ token
 struct semaphore_not_acquired : public std::runtime_error {
                                                           ^
/home/wwiv/git/core/../core/semaphore_file.h: In constructor ΓÇÿwwiv::core::semaphore_not_acquired::semaphore_not_acquired(const string&)ΓÇÖ:
    /home/wwiv/git/core/../core/semaphore_file.h:35:75: error: expected class-name before ΓÇÿ(ΓÇÖ token
   semaphore_not_acquired(const std::string& filename) : std::runtime_error(filename) {}
                                                                           ^
/home/wwiv/git/core/../core/semaphore_file.h:35:75: error: expected ΓÇÿ{ΓÇÖ before ΓÇÿ(ΓÇÖ token
core/CMakeFiles/core.dir/build.make:399: recipe for target 'core/CMakeFiles/core.dir/semaphore_file.cpp.o' failed
make[2]: *** [core/CMakeFiles/core.dir/semaphore_file.cpp.o] Error 1
CMakeFiles/Makefile2:212: recipe for target 'core/CMakeFiles/core.dir/all' failed
make[1]: *** [core/CMakeFiles/core.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2'

I know there are weird characters. I have CP437 set in putty and it does this for some reason using screen.

**Comment by wwiv** [comment]
strange.. compiles with GCC 6.3

**Comment by wwiv** [comment]
lemme try deb8

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/306c18547538fb1f4ebdc6ed0529dd3077aca6c4
