### ISSUE TITLE
Compiling 5.2 on CentOS 7 error/crash

### ISSUE THREAD

**Issue by k5jat** [wwivbbs/wwiv#998]
Taking advice, I decided to compile/install 5.2, instead of 5.3, on my CentOS 7 vps from the tarball. I have the proper gcc/g++ 4.9.2 installed.

During compiling, I received the following error:

"Scanning dependencies of target core
[  2%] Building CXX object core/CMakeFiles/core.dir/crc32.cpp.o
[  2%] Building CXX object core/CMakeFiles/core.dir/command_line.cpp.o
In file included from /usr/include/sys/stat.h:106:0,
                 from /home/wwiv/wwiv-wwiv_5.2.0/core/../deps/easylogging/easylogging++.h:343,
                 from /home/wwiv/wwiv-wwiv_5.2.0/core/../core/log.h:64,
                 from /home/wwiv/wwiv-wwiv_5.2.0/core/../core/stl.h:31,
                 from /home/wwiv/wwiv-wwiv_5.2.0/core/command_line.cpp:31:
/usr/include/bits/stat.h:106:31: error: expected unqualified-id before ‘[’ token
     __syscall_slong_t __unused[3];
                               ^
/usr/include/bits/stat.h:164:31: error: expected unqualified-id before ‘[’ token
     __syscall_slong_t __unused[3];
                               ^
make[2]: *** [core/CMakeFiles/core.dir/command_line.cpp.o] Error 1
make[1]: *** [core/CMakeFiles/core.dir/all] Error 2
make: *** [all] Error 2"

I setup a separate Debian 8 VPS and it compiles fine. I'm really not a fan of Debian...

**Comment by k5jat** [comment]
To rule out my compiled gcc/g++ compiled version not borking things up, I did a reinstall of CentOS 7 with the developer toolset and the results are the same.

**Comment by wwiv** [comment]
This was also fixed in a later commit

**Comment by wwiv** [comment]
Oh 5.2 yes this was an issue in 5.2

**Comment by wwiv** [comment]
Feel free to fit cherry pick this change and send. A pull request for it

https://github.com/wwivbbs/wwiv/commit/337e43d78d874bf61778d0782a8739e4a8911883

That's where I fixed it in 5.3

**Comment by wwiv** [comment]
You may also need to cherry pick other changes into 5.2 from 5.3

**Comment by granitepenguin** [comment]
Ok, so with more weirdness happening this way, we are probably better off figuring out 5.3.  If it's not working in 5.2, and we have known issues that were fixed in 5.3, let's not even waste the time and focus on making 5.3 work.

**Comment by granitepenguin** [comment]
Interestingly enough, I did a fresh build on CentOS 7 without dev tools or anything at all and it's working for me (i.e., I built a working 5.3 with the latest code using 4.8.5).

I think we need to figure out what's different between my environment and yours.

**Comment by granitepenguin** [comment]
clearing out and rebooting to make sure this isn't a fluke ;-)

**Comment by granitepenguin** [comment]
yeah, some leftovers needed to be cleared out.  Testing with devtoolset-3 right now

**Comment by granitepenguin** [comment]
Ok, so like I said, with you still having issues with 5.2, it will be better to focus on making 5.3 work.  

What I'm currently testing (and it works for me) is the latest CentOS7 with devtoolset-3 installed.

Maybe if you can document exactly what you are using, we can get a better feel for what isn't working.  It's not going to be worth the time to try to make 5.2 work, CentOS isn't officially supported yet, so it falls under getting it working in 5.3, not 5.2 (I had hoped 5.2 would be better, guess not).

However, the fact 5.3 does work for me and does not work for you means we just need to figure out why.

**Comment by k5jat** [comment]
5.3 compiles on CentOS 7, but the network2 segfaults. I'm currently using devtoolset-4. It has gcc/g++ 5.3.1, so it should work.

I tried compiling 5.3 with stock CentOS 7 and the 4.8.5 compiler, but trying to run cmake/make complained the compiler didn't support c++11. I haven't tried 5.2 with the 4.8.5 compiler.

**Comment by granitepenguin** [comment]
ok, so let's focus on the network2 segfault in 5.3

**Comment by granitepenguin** [comment]
CentOS is outside the scope of WWIV 5.2.  Reopened issue #989  for the segfault in network2
